name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install
        run: |
          npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Build
        run: npm run build
